### ISSUE TITLE
Skip persistence.xml

### ISSUE THREAD

**Issue by ekarlso** [oregami/dropwizard-guice-jpa-seed#1]
Hi, is it possible to get this working without using persistence.xml?

**Comment by sebeichholz** [comment]
Not that I know of, since I use Hibernate/JPA and not the JDBI module of dropwizard.

I found this SO question, but completely without persistence.xml seems to work only with Spring: http://stackoverflow.com/questions/1989672/create-entity-manager-without-persistence-xml

**Comment by ekarlso** [comment]
What is the diff?

Endre Karlson
5. okt. 2014 13:57 skrev "Sebastian Eichholz" notifications@github.com
følgende:

**Comment by sebeichholz** [comment]
You should google for "jdbi vs hibernate".
I e.g. use some advanced hibernate features like "Hibernate envers" for the versioning of data: http://docs.jboss.org/hibernate/orm/4.1/devguide/en-US/html/ch15.html

**Comment by sebeichholz** [comment]
To say it in another way: Hibernate/JPA does much more than JDBI.
What's the problem with the persistence.xml file? JPA/Hibernate is very mature and gives you the power to persist complex objects.

**Comment by ekarlso** [comment]
Doesnt dropwizard hibernate use jpa too?

Endre Karlson
5. okt. 2014 20:29 skrev "Sebastian Eichholz" notifications@github.com
følgende:

**Comment by sebeichholz** [comment]
There seems to be a module called "dropwizard-hibernate": http://dropwizard.io/manual/hibernate.html
Nevertheless I chose to use a "naked" JPA/Hibernate approach. Maybe I don't need to do so? Feel free to prove it! :-)

**Comment by ekarlso** [comment]
What do you mean by "naked" support ? Are you on IRC btw ? :)

**Comment by sebeichholz** [comment]
It was nice to meet you in IRC! :-)
As I said there, it might be possible to replace my approach with dropwizard-hibernate module, so that you can remove the persistence.xml completely.

**Comment by sebeichholz** [comment]
Hi! I did not forget your issue :-)
Take a look at my latest commits. The persistence.xml file is still there, but I read all the database configuration values from the YAML config file!
So technically the persistence.xml is not used and you can start the application with different database configurations from the command line.
