### ISSUE TITLE
Hibernate @OneToMany MappedBy not working... 

### ISSUE THREAD

**Issue by himanshuvirmani** [oregami/dropwizard-guice-jpa-seed#2]
Hey,

I tried the code by adding @OneToMany and @ManyToOne for tasks and subtasks. What works is that as soon the task is added the corresponding sub task is also added. What is not working is that task_id foreign key remains null. This is what I did : -

TASK.JAVA
@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch= FetchType.EAGER,   mappedBy = "task")
private final Set<SubTask> subTasks = new HashSet<>();

SUBTASK.JAVA
@ManyToOne
@JoinColumn(name = "task_id")
    private Task task;

This works in springs and other examples that I have seen on the web. Some how I am not able to debug whats going wrong.

**Comment by himanshuvirmani** [comment]
My Bad,,

I should have saved both entities Task and Subtask separately instead of trying to save subtask along with a task.. You can mark this as closed.. This is what i did : -

```
    Task t1 = new Task("task 1");
    t1.setDescription("This is task 1");
    t1.setLanguage(languageDao.findByExactName("english"));

    SubTask sub1 = new SubTask();
    sub1.setDescription("this a subtask 1");
    t1.addSubTask(sub1);
    ServiceResult<Task> taskServiceResult = taskService.createNewEntity(t1, null);

    sub1.setTask(t1);
    ServiceResult<SubTask> subtaskServiceResult = subTaskService.createNewEntity(sub1, null);
```

p.s. This works after implementing mappedBy to task and a host of other minor changes...

**Comment by sebeichholz** [comment]
Hi, take a look at my other similar project [oregami-server](https://github.com/oregami/oregami-server).
There I am using @ManyToOne und @OneToMany, e.g. between the entities [Game](https://github.com/oregami/oregami-server/blob/master/src/main/java/org/oregami/entities/Game.java#L44) and [ReleaseGroup](https://github.com/oregami/oregami-server/blob/master/src/main/java/org/oregami/entities/ReleaseGroup.java#L57). And it works.
